name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.CARD_GENERATOR_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          # UTC_OFFSET is optional, default to zero
          UTC_OFFSET: 7
